# Generated by Django 4.2.5 on 2023-10-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Last name"),
                ),
                ("birth_date", models.DateField(verbose_name="Date of birth")),
                ("subject", models.CharField(max_length=150, verbose_name="Subject")),
            ],
        ),
    ]
