name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add Black to PATH
        run: echo "::add-path::$(python -m site --user-site)\scripts"

      - name: Run Black with --check
        run: black . --check

      - uses: psf/black@stable
